#config_version=6

## MPF Main Machine Config File
#
# This file defines your system-wide properties like switches,
# drivers, ball devices, hardware platforms, and more. You can
# include everything here, or create sub-config files to be
# imported and merged with this one.

config:
  - config_switches.yaml
  - config_ball_devices.yaml
  - config_coils.yaml

modes:
  - attract
  - base
  - jets
  - hurryup

playfields:
  playfield:
    default_source_device: bd_balltruhe
    tags: default

virtual_platform_start_active_switches:
  - s_balltruhe_1
  - s_balltruhe_2
  - s_balltruhe_3
  - s_balltruhe_4
  - s_balltruhe_5
  - s_balltruhe_6
